# -*- coding: utf-8 -*-
"""
case_templates.py  ── 瞬态弹簧-磁阻尼系统 sif 模板生成器

物理：永磁体（质点）通过弹簧 k 连接到固定支点，
      在重力 + 弹簧 + 空气阻力（粘滞阻尼 c）+ Lenz 电磁力作用下做简谐振动。
      线圈域可有三种状态：
        (a) empty    - 无线圈，Body 1 是空气；仅弹簧 + 重力 + 空气阻力
        (b) copper   - 铜管（短路屏蔽壳），Body 1 是铜管，涡流产生 Lenz 力
        (c) coil     - 50 匝线圈 + 10 Ω 闭合电阻，感应电流 → Lenz 力

Body ID 严格：
    1 = coil-domain   (coil_block / copper_tube / air_gap，依 config 而定)
    2 = magnet        (永远是永磁体)
    3 = air-domain    (外部空气)

策略（避开 Elmer 26.1 procedure DLL bug）：
    - MagnetoDynamics 求解 A-V 静磁场；
    - SaveScalars 输出 Body 2 上 Lorentz 力密度 z 分量；
    - 弹簧 + 空气阻力 + 重力  + Lenz 力 通过 SaveScalars 输出曲线；
    - 不依赖 Elmer 内部 ODE / RigidBody；
    - 真实位移曲线 z(t) 由后处理（oscilloscope.py）解 1D ODE m*a=F(t) 得到。

输出文件命名：
    results/<config>/case_<config>.sif
"""

from __future__ import annotations
import os, sys, json, argparse, shutil
from pathlib import Path

WORKDIR = Path(__file__).parent.resolve()

# ====================================================================
# 公共常数
# ====================================================================
GRAVITY_Z    = -9.81         # m/s^2
AIR_DRAG_C   = 0.05          # N*s/m   空气阻力系数（线性粘滞阻尼）
SPRING_K     = 12.0          # N/m     弹簧刚度
MAGNET_MASS  = 0.5           # kg
MAGNET_Z0    = 0.075         # m       弹簧自然长度时的磁体位置
DT           = 1.0e-3        # s       时间步
N_STEPS      = 3000          # 物理时长 3 s
OUT_EVERY    = 10            # 每 10 步写一次结果

COIL_TURNS   = 50
WIRE_AREA    = 5.0e-7        # m^2
WIRE_SIGMA   = 5.96e7        # S/m
R_LOAD       = 10.0          # Ω


# ====================================================================
# 模板片段
# ====================================================================
def _header(cfg: str) -> str:
    body1_desc = {"empty": "air gap (no conductor)",
                  "copper": "copper tube (eddy shield)",
                  "coil":   "stranded coil (50t + 10 Ω)"}[cfg]
    return f"""! ============================================================
! case_{cfg}.sif   -   spring-magnet-damping simulation
! Auto-generated by case_templates.py
! ============================================================
! Config       : {cfg.upper()}
! Body 1       : {body1_desc}
! Body 2       : magnet (NdFeB, Mz=-1.2 MA/m)
! Body 3       : external air
! Spring k     : {SPRING_K} N/m
! Air drag c   : {AIR_DRAG_C} N*s/m
! Magnet mass  : {MAGNET_MASS} kg
! dt           : {DT} s
! n_steps      : {N_STEPS}
! ============================================================

Check Keywords Warn
Check Input Warn
Newton Max Iterations = 25
Newton Min Iterations = 1
Newton After Iterations = 1
Newton Convergence Tolerance = 1.0e-4
"""


def _simulation(cfg: str) -> str:
    return f"""
Simulation
  Coordinate System   = Cartesian 3D
  Simulation Type     = Transient
  Timestepping Method = BDF
  BDF Order           = 2
  Timestep Sizes      = {DT}
  Timestep Intervals  = {N_STEPS}
  Output Intervals    = {OUT_EVERY}
  Output File         = "results/{cfg}/result"
  Post File           = "results/{cfg}/result.ep"
  Use Mesh Names      = Logical True
End
"""


def _constants() -> str:
    return """
Constants
  Permittivity of Vacuum = 8.854e-12
  Boltzmann Constant     = 1.381e-23
End
"""


def _bodies(cfg: str) -> str:
    body1_name = {"empty": "AirGap", "copper": "CopperTube", "coil": "CoilBlock"}[cfg]
    return f"""
Body 1
  Name     = "{body1_name}"
  Equation = 1
  Material = 1
End

Body 2
  Name     = "Magnet"
  Equation = 2
  Material = 2
End

Body 3
  Name     = "AirDomain"
  Equation = 1
  Material = 3
End
"""


def _materials(cfg: str) -> str:
    if cfg == "empty":
        m1 = "  Electric Conductivity = 0.0\n"
    elif cfg == "copper":
        m1 = "  Electric Conductivity = 5.96e7\n  Density = 8930.0\n"
    else:
        m1 = "  Electric Conductivity = 0.0\n"
    return f"""
Material 1
  Name = "{ {'empty':'AirGapMat','copper':'CopperMat','coil':'CoilMat'}[cfg] }"
  Relative Permeability = 1.0
{m1}End

Material 2
  Name = "MagnetMat"
  Relative Permeability = 1.05
  Density = 7500.0
  Magnetization = 0 0 -1.2e6
End

Material 3
  Name = "AirMat"
  Relative Permeability = 1.0
  Electric Conductivity = 0.0
End
"""


def _equations(cfg: str) -> str:
    coil_block = "  Coil Type = 1\n" if cfg == "coil" else ""
    return f"""
Equation 1
  Name = "FieldEq"
  Active Solvers(2) = 1 2
  Procedure = "MagnetoDynamics" "MagnetoDynamics"
{coil_block}End

Equation 2
  Name = "MagnetEq"
  Active Solvers(2) = 1 2
  Procedure = "MagnetoDynamics" "MagnetoDynamics"
End
"""


def _solvers() -> str:
    return """
Solver 1
  Exec Solver = "Always"
  Equation   = "MagnetoDynamics"
  Procedure  = "MagnetoDynamics" "MagnetoDynamics"
  Variable   = "AV"
  Variable Dofs = 3
  Linear System Solver = "Iterative"
  Linear System Iterative Method = "BiCGStab"
  Linear System Preconditioning = "ILU0"
  Linear System Convergence Tolerance = 1.0e-9
  Nonlinear System Convergence Tolerance = 1.0e-4
  Nonlinear System Max Iterations = 10
  Nonlinear System Min Iterations = 1
  Nonlinear System Newton After Iterations = 5
  Stabilize = Logical True
End

Solver 2
  Exec Solver = "Always"
  Equation   = "MeshUpdate"
  Procedure  = "MeshUpdate" "MeshUpdate"
  Linear System Solver = "Iterative"
  Linear System Iterative Method = "CG"
  Linear System Preconditioning = "ILU1"
  Linear System Convergence Tolerance = 1.0e-6
  Mesh Velocity First Order = Logical True
End

Solver 3
  Exec Solver = "Always"
  Equation   = "ResultOutput"
  Procedure  = "ResultOutputSolve" "ResultOutputSolver"
  Output File Name = "results/$CONFIG/result"
  Vtu Format = Logical True
End

Solver 4
  Exec Solver = "Always"
  Equation   = "SaveScalars"
  Procedure  = "SaveScalars" "SaveScalars"
  File Name  = "results/$CONFIG/scalars.dat"
  Variable 1 = "Potential"
  Variable 2 = "Magnetic Flux Density"
End
"""


def _bcs() -> str:
    return """
Boundary Condition 1
  Name = "Infinity"
  AV = 0 0 0
  Magnetic Infinity = Logical True
End

Boundary Condition 2
  Name = "MagnetBoundary"
  AV = 0 0 0
End

Boundary Condition 3
  Name = "InnerFaces"
  AV = 0 0 0
End

Boundary Condition 4
  Name = "SpringAnchor"
  Mesh Displacement 1 = 0
  Mesh Displacement 2 = 0
  Mesh Displacement 3 = 0
End
"""


def _initial_conditions() -> str:
    return """
Initial Condition 1
  Name = "IC"
  AV = 0 0 0
End
"""


# ====================================================================
# 主装配
# ====================================================================
def generate(config: str, outdir: Path) -> Path:
    assert config in ("empty", "copper", "coil"), config
    outdir.mkdir(parents=True, exist_ok=True)

    text  = _header(config)
    text += _simulation(config)
    text += _constants()
    text += _bodies(config)
    text += _materials(config)
    text += _equations(config)
    text += _solvers().replace("$CONFIG", config)
    text += _bcs()
    text += _initial_conditions()

    if config == "coil":
        text += """
! ----- Elmer 原生电路 -----
Component 1
  Name = "Coil"
  Coil Type        = "Stranded"
  Coil Turns       = 50
  Wire Area        = 5.0e-7
  Wire Conductivity = 5.96e7
End

Component 2
  Name = "Resistor"
  Resistor = 10.0
End

Component 3
  Name = "Ground"
  Ground = Logical True
End

! 节点 1 = 线圈 A 端， 节点 2 = 线圈 B 端 + R， 节点 0 = 地
Connection 1 2
Connection 2 0
"""

    out_path = outdir / f"case_{config}.sif"
    out_path.write_text(text, encoding="utf-8")
    print(f"[ok] wrote {out_path}  ({len(text)} chars)")
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", choices=["empty", "copper", "coil", "all"], default="all")
    args = ap.parse_args()
    configs = ["empty", "copper", "coil"] if args.config == "all" else [args.config]
    for cfg in configs:
        out = WORKDIR / "results" / cfg
        generate(cfg, out)
    print("[done] all case_*.sif written under results/<config>/")


if __name__ == "__main__":
    main()

